---

############# Project settings. ################################################
# These are typically shared amongst your team for a given project.
# See https://github.com/codeenigma/ce-vm/wiki/en/latest/config/config/ on where to store
# other variables.
# Only "basic" settings are configured here, to access and override more
# advanced ones, refer to the main default config file at
# https://github.com/codeenigma/ce-vm/blob/master/config.yml.
################################################################################

####### Base settings.

# Project name. Only use lower alphanumeric chars, no underscore or hyphen.
project_name: upd
# Project type, can be either drupal, symfony, wordpress pr php_generic.
project_type: drupal
# Webroot, relative to project folder.
webroot: www
#webroot: web
#webroot: public

# Symfony local dev environment.
symfony_local_env: dev
#symfony_local_env: local

####### Services/containers.
# Each of these service supports its own configuration.
# See service.$NAME.yml for each.
services: 
  - log
  - dashboard
  - fpm
  - nginx
  - mysql
  - memcached
  - cli
  - solr
  #- mkdocs
  #- nodejs
  #- redis
  #- haproxy
  #- nightwatch
  #- base

####### Common settings.

# This could be set at the 'service level', in service.fpm.yml or service.cli.yml.
# Setting it here ensure fpm and cli use the same version.
php_version: 7.2
