version: '2'

services:
  solr7:
    image: solr:7.5
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/d8
      - ./tests/solr-conf/7.x:/solr-conf/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - d8
      - /solr-conf
volumes:
  data:
