const config = {
  context: {
    paragraphs: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam placerat sagittis lacus sit amet ultricies. Cras sit amet nulla cursus, ornare velit eu, volutpat risus. Proin quis libero nec dolor sodales tincidunt. Nam rhoncus congue diam, ultricies fringilla nisl eleifend id. Donec id dolor id ipsum facilisis aliquam. Curabitur eget nibh pretium leo porttitor placerat sit amet efficitur sem. Sed vitae justo justo. Cras posuere diam non mi blandit gravida. Aenean feugiat lectus neque, a pharetra diam tempor eu. Sed iaculis velit et nisl tincidunt venenatis.',
      'Morbi in rutrum orci, id pulvinar sem. Vestibulum feugiat purus sapien, eget luctus enim lacinia tempus. Vestibulum eleifend dictum nibh, eget commodo mi lacinia eget. Cras in justo quis justo tristique imperdiet. Etiam luctus orci vel mauris tempus pharetra. Suspendisse ut posuere arcu. Suspendisse posuere ullamcorper consectetur.',
      'Phasellus euismod varius diam at pulvinar. Fusce lacinia ultrices sem non sagittis. Quisque ac arcu ornare, elementum urna sit amet, accumsan est. Cras tempor, nisi a vestibulum aliquam, justo eros aliquet nisl, ut sagittis nibh velit eu tellus. Fusce iaculis malesuada nisi, feugiat dictum est blandit at. Sed malesuada justo nec velit semper, a lobortis lorem volutpat. Etiam id ligula id urna maximus malesuada. Nam pharetra, justo ac malesuada convallis, nisi magna congue nulla, in hendrerit nisl metus non arcu. Nunc auctor orci turpis, facilisis tristique mi tincidunt vel. Vivamus sem arcu, pharetra quis augue nec, consectetur dictum dui. Proin fermentum purus sed mauris euismod, sit amet tincidunt arcu malesuada. Quisque dictum semper felis id tempus. Aliquam erat volutpat. Quisque non orci vehicula, elementum lectus ut, vestibulum magna.',
      'Nunc vel vulputate libero. Cras nisl nibh, laoreet vel sem ac, porta hendrerit augue. Praesent sollicitudin, mi sed faucibus vestibulum, turpis sapien volutpat odio, ut dictum ligula velit id mi. Aenean finibus elementum laoreet. Morbi pretium porttitor vestibulum. In eu lorem vel metus tincidunt consectetur ac vulputate felis. Proin sed convallis ex. Curabitur eget turpis elementum, pulvinar diam eget, bibendum diam. Nullam quis tempor odio. Maecenas sodales ex et elit sodales, ac vestibulum enim maximus. Aenean at sapien rhoncus, aliquam nunc id, posuere mauris.',
      'Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris ullamcorper eget leo ac malesuada. Pellentesque velit magna, iaculis at felis nec, ullamcorper eleifend erat. Donec eu dui eu ipsum pulvinar egestas in eget odio. Nullam ac venenatis est. Nunc molestie dictum lorem, non fermentum dui gravida at. Integer placerat libero quis quam varius mattis. Maecenas id sodales est. Aliquam pulvinar lectus in magna malesuada viverra. Curabitur tortor mauris, maximus id mi at, aliquam ullamcorper lectus.'
    ]
  }
}

module.exports = config
