<?php

/**
 * @file
 * UPD basic page module file.
 */

/**
 * Implements hook_preprocess_node().
 */
function upd_basic_page_preprocess_node(&$variables) {
  _upd_basic_page_preprocess_node_sections($variables);
}

/**
 * Alter node rendering to add pseudo "vertical tabs".
 *
 * @see upd_preprocess_node()
 */
function _upd_basic_page_preprocess_node_sections(&$variables) {
  if ($variables['view_mode'] !== 'full') {
    return;
  }

  $node = $variables['node'];
  if (!isset($node->field_sections)) {
    return;
  }
  $i = 0;
  $variables['content']['vertical'][$i]['title'] = 'Summary';
  $variables['content']['vertical'][$i]['url'] = 'intro';
  foreach ($node->field_sections as $item) {
    $i++;
    $variables['content']['vertical'][$i]['title'] = $item->entity->get('field_title')
      ->getValue()[0]['value'];
    $variables['content']['vertical'][$i]['url'] = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $item->entity->get('field_title')
    ->getValue()[0]['value'])));
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function upd_basic_page_preprocess_paragraph(&$variables) {
  if (in_array($variables['paragraph']->bundle(), ['file_download'])) {
    $paragraph = $variables['paragraph'];
    foreach ($paragraph->field_download_files as $key => $item) {
      $file_uri = $item->entity->getFileUri();
      $variables['content']['file_info'][$key]['url'] = file_create_url($file_uri);
      $variables['content']['file_info'][$key]['extension'] = pathinfo($file_uri, PATHINFO_EXTENSION);
      $variables['content']['file_info'][$key]['image'] = render($variables['content']['field_download_files'][$key]);
    }
  }
}

/**
 * Implements hook_preprocess_field().
 *
 * @todo this should belong to a upd_user module.
 * Left here as it is only used in basic_page for now.
 */
function upd_basic_page_preprocess_field(&$variables, $hook) {
  if ($variables['field_name'] !== 'field_photo') {
    return;
  }
  if ($variables['entity_type'] !== 'user') {
    return;
  }
  $class = $variables['element']['#view_mode'] == 'tile' ? 'team-tile__image' : 'profile__image';
  foreach ($variables['items'] as $delta => $item) {
    $variables['items'][$delta]['content']['#item_attributes']['class'][] = $class;
  }
}
