<?php

/**
 * @file
 */

use Drupal\Core\Block\BlockPluginInterface;
/**
 * @file
 * UPD case study module file.
 */
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_block_view_alter().
 *
 * NOTE: You MUST implement this hook if you want your block plugins to work
 * even if you do nothing inside the function body!
 */
function upd_case_study_block_view_alter(array &$build, BlockPluginInterface $block) {

}

/**
 * Implements hook_preprocess_node().
 */
function upd_case_study_preprocess_node(&$variables) {
  _upd_case_study_preprocess_node_vertical_tabs($variables);
  _upd_case_study_preprocess_node_tags($variables);
  _upd_case_study_preprocess_node_thumbnail($variables);
  _upd_case_study_preprocess_node_nextprevious($variables);
}

/**
 * Alter node rendering to get image thumbnail url.
 *
 * @see upd_preprocess_node()
 */
function _upd_case_study_preprocess_node_thumbnail(&$variables) {
  if ($variables['view_mode'] !== 'teaser') {
    return;
  }
  $node = $variables['node'];
  if (!isset($node->field_thumbnail)) {
    return;
  }
  $variables['content']['thumbnail_url'] = ImageStyle::load('thumbnail_list')->buildUrl($node->field_thumbnail[0]->entity->uri->value);
}

/**
 * Alter node rendering to add pseudo "vertical tabs".
 *
 * @see upd_preprocess_node()
 */
function _upd_case_study_preprocess_node_vertical_tabs(&$variables) {
  if ($variables['view_mode'] !== 'full') {
    return;
  }
  $node = $variables['node'];
  if (!isset($node->field_vertical_tab)) {
    return;
  }
  $i = 0;
  $variables['content']['vertical'][$i]['title'] = 'Summary';
  $variables['content']['vertical'][$i]['url'] = 'intro';
  foreach ($node->field_vertical_tab as $item) {
    $i++;
    $variables['content']['vertical'][$i]['title'] = $item->entity->get('field_title')->getValue()[0]['value'];
    $variables['content']['vertical'][$i]['url'] = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $item->entity->get('field_title')->getValue()[0]['value'])));
  }
}

/**
 * Gather all taxonomy fields into a single place for theming.
 *
 * @see upd_preprocess_node()
 */
function _upd_case_study_preprocess_node_tags(&$variables) {
  $node = $variables['node'];
  if ($node->bundle() !== 'case_study') {
    return;
  }
  $fields = [
    'field_impact_of_work',
  ];
  foreach ($fields as $field) {
    foreach ($node->get($field)->referencedEntities() as $term) {
      $color = $term->get('field_color')->value;
      $node->updTags[$term->id()] = [
        'label' => $term->label(),
        'color' => !empty($color) ? $color : 'f8533d',
      ];
    }
  }
}

/**
 * Getting nextpreviousblock and pass it to template.
 *
 * @see upd_preprocess_node()
 */
function _upd_case_study_preprocess_node_nextprevious(&$variables) {
  $nextprevious_block = \Drupal::entityManager()->getStorage('block')->load('nextpreviousblock');
  if (!empty($nextprevious_block)) {
    $nextprevious_block_content = \Drupal::entityManager()
      ->getViewBuilder('block')
      ->view($nextprevious_block);
    if ($nextprevious_block_content) {
      $variables['content']['nextpreviousblock'] = $nextprevious_block_content;
    }
  }
}

/**
 * Implements hook_preprocess_paragraphs().
 *
 * @todo filter on paragraph bundle.
 */
function upd_case_study_preprocess_paragraph(&$variables) {
  if (!empty($variables['content']['field_title'][0]['#context']['value'])) {
    $variables['content']['paragraph_url'] = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $variables['content']['field_title'][0]['#context']['value'])));
  }
}
