module:
  block: 0
  breakpoint: 0
  config: 0
  content_moderation: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  entity_reference_revisions: 0
  field: 0
  file: 0
  filter: 0
  image: 0
  link: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  workbench: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
