<?php

/**
 * @file
 * UPD landing page module file.
 */

/**
 * Implements hook_preprocess_node().
 */
function upd_landing_page_preprocess_node(&$variables) {
  _upd_case_study_preprocess_node_featured_news($variables);
}

/**
 * Alter node rendering to add "featured news"
 *
 * @see upd_preprocess_node()
 */
function _upd_case_study_preprocess_node_featured_news(&$variables) {
  if ($variables['view_mode'] !== 'full') {
    return;
  }
  $node = $variables['node'];
  if (!isset($node->field_featured_articles)) {
    return;
  }
  $variables['featured_news'] = views_embed_view('featured_news', 'featured_news');
}
