<?php

/**
 * @file
 * Contains media_upload.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_upload_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the media_upload module.
    case 'help.page.media_upload':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows uploading files in bulk and converting them to media entities.') . '</p>';
      return $output;

    default:
  }
}
