<?php

/**
 *  Implements hook_theme().
 */
function upd_video_theme($existing, $type, $theme, $path) {
  return [
    'upd_video_lightbox' => [
      'variables' => [
        'embed' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_video_embed_iframe__youtube().
 */
function upd_video_preprocess_video_embed_iframe__youtube(&$variables) {
  // Swap youtube.com for youtube-nocookie.com to prevent cookies being sent.
  $variables['url'] = str_replace('youtube.com', 'youtube-nocookie.com', $variables['url']);
}
