name: Config Ignore
type: module
description: Ignore certain configuration during import
# core: 8.x
package: Configuration
configure: config_ignore.settings
dependencies:
  - config

# Information added by Drupal.org packaging script on 2017-03-24
version: '8.x-1.4'
core: '8.x'
project: 'config_ignore'
datestamp: 1490346197
