---

- hosts: all
  become: yes

  tasks:
    - name: Ensure Drupal "files" permissions
      file:
        path: '/vagrant/www/sites/default/files'
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: 0777
    - name: Create local private files folder.
      file:
        path: '/vagrant/private'
        state: directory
        owner: www-data
        group: www-data
    - name: Ensure "private" folder permissions.
      file:
        path: '/vagrant/private'
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: 0777
